server:
  port: 9000

spring:

  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}

  cloud:
    gateway:
      server:
        webmvc:
          routes:

            - id: kpi-service
              uri: ${KPI_SERVICE_URI}
              predicates:
                - Path=/api/kpi/**
              filters:
                - StripPrefix=2

            - id: data-service
              uri: ${DATA_SERVICE_URI}
              predicates:
                - Path=/api/data/**
              filters:
                - StripPrefix=2

            - id: dashboard-service
              uri: ${DASHBOARD_SERVICE_URI}
              predicates:
                - Path=/api/dashboard/**
              filters:
                - StripPrefix=2

      globalcors:
        corsConfigurations:
          '[/**]':

            allowedOrigins:
              - ${FRONTEND_ORIGIN}

            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS

            allowedHeaders:
              - "*"

            allowCredentials: true

auth0:
  audience: ${OAUTH2_AUDIENCE}
  roles-claim: ${AUTH0_ROLES_CLAIM}